### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by user706** [commschamp/cc.demo1.generated#1]
Hi,

am I correct in believing there's an error in this line: [link](https://github.com/arobenko/cc.demo1.generated/blob/7a9b8f53c359ed7016362c6c77483b6d26a1dfad/include/demo1/Version.h#L21) (minor-version duplicated, no patch-version)
?

**Comment by arobenko** [comment]
Yes, thank you.
The bug is in [code generator](https://github.com/arobenko/commsdsl). I'll introduce a hotfix within a couple of days.

**Comment by arobenko** [comment]
Fixed in v1.4.1 of [commsdsl](https://github.com/arobenko/commsdsl/) project. The fix is visible in v0.6.1 release of this one.
